### ISSUE TITLE
PHP 8.1 deprecation warning

### ISSUE THREAD

**Issue by jjozsi** [BlowbackAgency/EmailObfuscation#13]
PHP 8 and PHP 8.1 throws a deprecation warning:
is_nan(): Passing null to parameter #1 ($num) of type float is deprecated in EmailObfuscation.module on line 247 and 248.
Changing line 240 from
`$c2 = $c3 = null;`
to
`$c2 = $c3 = 0;`
seems to fix it.

**Comment by Roope** [comment]
Fixed in #16
